#include "CodeGenerate/CodeGenerateSource.h"
#include "Instrumentor.h"
#include "CodeGenerate/CodeGenerateHeader.h"

namespace Reflect
{
	void CodeGenerateSource::GenerateSource(const FileParsedData& data, std::ofstream& file, const ReflectAddtionalOptions& addtionalOptions)
	{
		REFLECT_PROFILE_FUNCTION();

		file << " // This file is auto generated by the Reflect tool please don't modify this file as it will be overwritten.\n";

		//CodeGenerate::IncludeHeader(data.FileName + ReflectFileGeneratePrefix + ".h", file);
		if (!addtionalOptions.options.at(Reflect_CMD_Option_PCH_Include).empty())
		{
			CodeGenerate::IncludeHeader(addtionalOptions.options.at(Reflect_CMD_Option_PCH_Include), file);
		}
		CodeGenerate::IncludeHeader("../" + data.FileName + ".h", file);
		file << "\n";

		for (const std::string& include : data.CPPIncludes)
		{
			CodeGenerate::IncludeHeader(include, file);
		}
		file << "\n";

		for (auto& reflectData : data.ReflectData)
		{
#ifdef REFLET_TYPE_INFO
			WriteGenerateTypeInfo(reflectData, file, addtionalOptions);
#endif
			WriteMemberProperties(reflectData, file, addtionalOptions);
			WriteFunctionGet(reflectData, file, addtionalOptions);
			WriteMemberGet(reflectData, file, addtionalOptions);
		}
	}

	void CodeGenerateSource::WriteMemberProperties(const ReflectContainerData& data, std::ofstream& file, const ReflectAddtionalOptions& addtionalOptions)
	{
		auto getMemberProps = [](const std::vector<std::string>& flags) -> std::string
		{
			if (flags.size() == 0)
			{
				return "{ }";
			}

			std::string value;
			value += "{";
			for (auto const& flag : flags)
			{
				if (flag != flags.back())
				{
					value += "\"" + flag + "\"" + ", ";
				}
			}
			value += "\"" + flags.back() + "\"" + "}";
			return value;
		};

		if (data.Members.size() > 0)
		{
			file << "Reflect::ReflectMemberProp " + data.Name + "::__REFLECT_MEMBER_PROPS__[" + std::to_string(data.Members.size()) + "] = {\n";
			for (const auto& member : data.Members)
			{
				file << "\tReflect::ReflectMemberProp(\"" + member.Name + 
					"\", new Reflect::ReflectTypeCPP<" + CodeGenerateHeader::GetType(member, false) + ">(Reflect::EReflectType::Member), " +
					 "__REFLECT__" + member.Name + "(), " + 
					getMemberProps(member.ContainerProps) + "),\n";
			}
			file << "};\n\n";
		}
	}

	void CodeGenerateSource::WriteMemberGet(const ReflectContainerData& data, std::ofstream& file, const ReflectAddtionalOptions& addtionalOptions)
	{
		file << "Reflect::ReflectMember " + data.Name + "::GetMember(const char* memberName)\n{\n";
		if (data.Members.size() > 0)
		{
			file << "\tfor(const auto& member : __REFLECT_MEMBER_PROPS__)\n\t{\n";
			file << "\t\tif(memberName == member.Name)\n";
			file << "\t\t{\n";
			file << "\t\t\t//CheckFlags\n";
			file << "\t\t\treturn " + MemberFormat() + "; \n";
			file << "\t\t}\n";
			file << "\t}\n";
		}
		file << "\treturn __super::GetMember(memberName);\n";
		file << "}\n\n";

		file << "std::vector<Reflect::ReflectMember> " + data.Name + "::GetMembers(std::vector<std::string> const& flags)\n{\n";
		file << "\tstd::vector<Reflect::ReflectMember> members = __super::GetMembers(flags);\n";
		if (data.Members.size() > 0)
		{
			file << "\tfor(auto& member : __REFLECT_MEMBER_PROPS__)\n\t{\n";
			file << "\t\tif(member.ContainsProperty(flags))\n";
			file << "\t\t{\n";
			file << "\t\t\tmembers.push_back(" + MemberFormat() + "); \n";
			file << "\t\t}\n";
			file << "\t}\n";
		}
		file << "\treturn members;\n";
		file << "}\n\n";

		file << "std::vector<Reflect::ReflectMember> " + data.Name + "::GetAllMembers()\n{\n";
		file << "\tstd::vector<Reflect::ReflectMember> members = __super::GetAllMembers();\n";
		if (data.Members.size() > 0)
		{
			file << "\tfor(auto& member : __REFLECT_MEMBER_PROPS__)\n\t{\n";
			file << "\t\tmembers.push_back(" + MemberFormat() + "); \n";
			file << "\t}\n";
		}
		file << "\treturn members;\n";
		file << "}\n\n";
	}

	void CodeGenerateSource::WriteFunctionGet(const ReflectContainerData& data, std::ofstream& file, const ReflectAddtionalOptions& addtionalOptions)
	{
#ifdef REFLET_TYPE_INFO
		file << "Reflect::ReflectTypeInfo " + data.Name + "::GetTypeInfo()\n{\n";
		file << "\treturn Reflect::GenerateTypeInfoForType<" + data.Name + ">().GetTypeInfo(nullptr);\n";
		file << "}\n\n";
		file << "Reflect::ReflectTypeInfo " + data.Name + "::GetTypeInfo(" + data.Name + "* classPtr)\n{\n";
		file << "\treturn Reflect::GenerateTypeInfoForType<" + data.Name + ">().GetTypeInfo(classPtr);\n";
		file << "}\n\n";
#endif

		file << "Reflect::ReflectFunction " + data.Name + "::GetFunction(const char* functionName)\n{\n";
		for (const auto& func : data.Functions)
		{
			file << "\tif(functionName == \"" + func.Name + "\")\n";
			file << "\t{\n";
			file << "\t\treturn Reflect::ReflectFunction(this, " + data.Name + "::__REFLECT_FUNC__" + func.Name + ");\n";
			file << "\t}\n";
		}
		file << "\treturn __super::GetFunction(functionName);\n";
		file << "}\n\n";
	}

#ifdef REFLET_TYPE_INFO
	void CodeGenerateSource::WriteGenerateTypeInfo(const ReflectContainerData& data, std::ofstream& file, const ReflectAddtionalOptions& addtionalOptions)
	{
		auto generateFunctions = [&data]() -> std::string
		{
			auto generateFunctionArgs = [&data]()->std::string
			{
				auto generateSingleArg = [&data](const ReflectTypeNameData& arg) -> std::string
				{
					std::string str;
					str += "std::make_unique<ReflectTypeCPP<" + arg.RawType + ">>(Reflect::EReflectType::Parameter, \"" + arg.Name + "\")";
					return str;
				};

				std::string str;

				for (const auto& func : data.Functions)
				{
					str += "\t\tstd::vector<std::unique_ptr<ReflectType>> " + func.Name + "_Args;\n";
					for (const auto& arg : func.Parameters)
					{
						str += "\t\t" + func.Name + "_Args.emplace_back(" + generateSingleArg(arg) + ");\n";
					}
				}
				return str;
			};

			auto generateSingleFunction = [&data](const ReflectFunctionData& func) -> std::string
			{
				std::string str;
				str += "std::make_unique<Reflect::ReflectTypeFunction>";
				str += "((void*)ownerClass, ";
				str += "ownerClass->__REFLECT_FUNC__" + func.Name + ", ";
				str += "std::make_unique<ReflectTypeCPP<" + func.Type + ">>(Reflect::EReflectType::Function, \"" + func.Name + "\"), ";
				str += "std::move(" + func.Name + "_Args))";
				return str;
			};

			std::string result = "std::vector<std::unique_ptr<Reflect::ReflectTypeFunction>> GenerateFunctions(" + data.Name + "* ownerClass)\n\t{\n";
			
			result += generateFunctionArgs() + "\n";

			result += "\t\tstd::vector<std::unique_ptr<Reflect::ReflectTypeFunction>> funcs;\n";
			for (const auto& f : data.Functions)
			{
				result += "\t\tfuncs.push_back(" + generateSingleFunction(f) + ");\n";
			}
			result += "\t\treturn funcs;\n";
			result += "\t}\n";
			return result;
		};

		file << "template<>\n";
		file << "class Reflect::GenerateTypeInfoForType<" + data.Name + ">\n{\n";
		file << "public:\n";
		file << "\tReflect::ReflectTypeInfo GetTypeInfo(" + data.Name + "* ownerClass)\n\t{\n";
		file << "\t\tstd::vector<std::unique_ptr<Reflect::ReflectTypeFunction>> functions = GenerateFunctions(ownerClass);\n";
		file << "\t\treturn ReflectTypeInfo(ownerClass, ";
		file << "std::make_unique<ReflectTypeCPP<" + data.Name + ">>(Reflect::EReflectType::Class), ";
		file << "std::move(functions)); \n";
		file << "\t}\n";
		WRITE_PRIVATE();
		file << "\t" + generateFunctions() + "\n";
		file << "};\n\n";
	}
#endif

	std::string CodeGenerateSource::MemberFormat()
	{
		return "Reflect::ReflectMember(member.Name, member.Type, ((char*)this) + member.Offset)";
	}

	//void CodeGenerateSource::WriteFunctionBindings(const ReflectContainerData& data, std::ofstream& file)
	//{
	//	file << "\t" + data.Name << "* ptr = dynamic_cast<" + data.Name + "*>(this);\n";
	//	file << "\tassert(ptr != nullptr && \"[" + data.Name + ContainerPrefix + "::" + "SetupReflectBindings()] 'ptr' should not be null.\");\n\n";
	//	for (auto& func : data.Functions)
	//	{
	//		// Write to the auto generated file binding a function then setting up a "FuncWrapper" for which we can then call the function from.
	//		file << "\tauto " + func.Name + "Func = std::bind(&" + data.Name + "::" + func.Name + ", ptr);\n";
	//		file << "\tReflect::FuncWrapper " + func.Name + "Wrapper(" + func.Name + "Func);\n";
	//		file << "\t__super::AddFunction(" + func.Name + ", " + func.Name + "Wrapper);\n";
	//	}
	//	file << "\n";
	//}
}
